import type { MLSListing, Client, DashboardStats, Note } from "@/types";

export const mlsListings: MLSListing[] = [
  {
    mlsId: "MLS-2024-001",
    address: "4821 Westbrook Lane",
    city: "Austin",
    state: "TX",
    zip: "78731",
    listPrice: 875000,
    originalListPrice: 925000,
    sqft: 3240,
    bedrooms: 4,
    bathrooms: 3.5,
    garageSpaces: 2,
    yearBuilt: 2018,
    lotSize: 0.28,
    propertyType: "Single Family",
    status: "Active",
    daysOnMarket: 14,
    listDate: "2024-04-08",
    closedDate: null,
    closedPrice: null,
    description: "Stunning modern home in West Austin. Open concept living with chef's kitchen, quartz countertops, and premium appliances. Primary suite features spa bath and walk-in closet.",
    features: ["Pool", "Smart Home", "Solar Panels", "Outdoor Kitchen", "Wine Cellar"],
    photos: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Jordan Reeves",
    agentId: "AGT-001",
    brokerageName: "Atrium Realty Group",
    latitude: 30.3399,
    longitude: -97.7857,
    hoaFee: 125,
    taxAnnual: 14200,
    pricePerSqft: 270,
    openHouseDate: "2024-04-27",
  },
  {
    mlsId: "MLS-2024-002",
    address: "1103 Ridgecrest Drive",
    city: "Austin",
    state: "TX",
    zip: "78746",
    listPrice: 1250000,
    originalListPrice: 1250000,
    sqft: 4100,
    bedrooms: 5,
    bathrooms: 4,
    garageSpaces: 3,
    yearBuilt: 2021,
    lotSize: 0.42,
    propertyType: "Single Family",
    status: "Pending",
    daysOnMarket: 5,
    listDate: "2024-04-17",
    closedDate: null,
    closedPrice: null,
    description: "Luxury new construction in Westlake. Soaring ceilings, white oak floors, and resort-style backyard. Sought-after Eanes ISD.",
    features: ["Pool", "Spa", "Game Room", "Media Room", "3-Car Garage", "Guest Suite"],
    photos: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=80"],
    agentName: "James Okafor",
    agentId: "AGT-002",
    brokerageName: "Atrium Realty Group",
    latitude: 30.2969,
    longitude: -97.8192,
    hoaFee: 200,
    taxAnnual: 22400,
    pricePerSqft: 305,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-003",
    address: "512 East 6th Street #4B",
    city: "Austin",
    state: "TX",
    zip: "78701",
    listPrice: 445000,
    originalListPrice: 465000,
    sqft: 1180,
    bedrooms: 2,
    bathrooms: 2,
    garageSpaces: 1,
    yearBuilt: 2016,
    lotSize: 0,
    propertyType: "Condo",
    status: "Active",
    daysOnMarket: 31,
    listDate: "2024-03-22",
    closedDate: null,
    closedPrice: null,
    description: "Chic downtown condo with sweeping city views. Floor-to-ceiling windows, designer finishes, and rooftop amenities. Walking distance to dining, entertainment, and the hike-and-bike trail.",
    features: ["Concierge", "Rooftop Pool", "Fitness Center", "City Views", "EV Charging"],
    photos: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Jordan Reeves",
    agentId: "AGT-001",
    brokerageName: "Atrium Realty Group",
    latitude: 30.2672,
    longitude: -97.7398,
    hoaFee: 480,
    taxAnnual: 8900,
    pricePerSqft: 377,
    openHouseDate: "2024-04-28",
  },
  {
    mlsId: "MLS-2024-004",
    address: "7730 Mesa Verde Court",
    city: "Cedar Park",
    state: "TX",
    zip: "78613",
    listPrice: 598000,
    originalListPrice: 598000,
    sqft: 2850,
    bedrooms: 4,
    bathrooms: 3,
    garageSpaces: 2,
    yearBuilt: 2015,
    lotSize: 0.19,
    propertyType: "Single Family",
    status: "Active",
    daysOnMarket: 8,
    listDate: "2024-04-14",
    closedDate: null,
    closedPrice: null,
    description: "Beautifully maintained home in Leander ISD. Upgrades throughout including kitchen remodel, new roof, and backyard entertaining space.",
    features: ["Covered Patio", "Updated Kitchen", "New Roof", "Sprinkler System"],
    photos: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Marcus Webb",
    agentId: "AGT-003",
    brokerageName: "Atrium Realty Group",
    latitude: 30.5052,
    longitude: -97.8203,
    hoaFee: 60,
    taxAnnual: 11200,
    pricePerSqft: 210,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-005",
    address: "2244 South Congress Ave #12",
    city: "Austin",
    state: "TX",
    zip: "78704",
    listPrice: 325000,
    originalListPrice: 349000,
    sqft: 890,
    bedrooms: 1,
    bathrooms: 1,
    garageSpaces: 1,
    yearBuilt: 2012,
    lotSize: 0,
    propertyType: "Condo",
    status: "Active",
    daysOnMarket: 22,
    listDate: "2024-03-31",
    closedDate: null,
    closedPrice: null,
    description: "Hip SoCo condo steps from Austin's best restaurants and boutiques. Modern interior with concrete floors, chef's kitchen, and private balcony.",
    features: ["Balcony", "Pet Friendly", "Gated Community", "Fitness Center"],
    photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80"],
    agentName: "James Okafor",
    agentId: "AGT-002",
    brokerageName: "Atrium Realty Group",
    latitude: 30.2481,
    longitude: -97.7502,
    hoaFee: 310,
    taxAnnual: 6500,
    pricePerSqft: 365,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-006",
    address: "910 Barton Hills Drive",
    city: "Austin",
    state: "TX",
    zip: "78704",
    listPrice: 1650000,
    originalListPrice: 1750000,
    sqft: 4800,
    bedrooms: 5,
    bathrooms: 5,
    garageSpaces: 2,
    yearBuilt: 2020,
    lotSize: 0.55,
    propertyType: "Single Family",
    status: "Closed",
    daysOnMarket: 18,
    listDate: "2024-03-01",
    closedDate: "2024-04-12",
    closedPrice: 1610000,
    description: "Spectacular Barton Hills estate with panoramic Greenbelt views. Architect-designed with seamless indoor-outdoor living, infinity pool, and detached guest house.",
    features: ["Infinity Pool", "Guest House", "Greenbelt Views", "Elevator", "Smart Home", "Wine Room"],
    photos: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Jordan Reeves",
    agentId: "AGT-001",
    brokerageName: "Atrium Realty Group",
    latitude: 30.2389,
    longitude: -97.7728,
    hoaFee: null,
    taxAnnual: 31000,
    pricePerSqft: 344,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-007",
    address: "3388 Lakeway Boulevard",
    city: "Lakeway",
    state: "TX",
    zip: "78734",
    listPrice: 785000,
    originalListPrice: 785000,
    sqft: 3680,
    bedrooms: 4,
    bathrooms: 3.5,
    garageSpaces: 3,
    yearBuilt: 2019,
    lotSize: 0.34,
    propertyType: "Single Family",
    status: "Active",
    daysOnMarket: 3,
    listDate: "2024-04-19",
    closedDate: null,
    closedPrice: null,
    description: "Exceptional lake-area home in gated Lakeway community. Open plan, butler's pantry, game room, and oversized 3-car garage. Access to Lake Travis and award-winning LTISD.",
    features: ["Lake Access", "Game Room", "Butler's Pantry", "Gated", "3-Car Garage"],
    photos: ["https://images.unsplash.com/photo-1605146768851-eda79da39897?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Marcus Webb",
    agentId: "AGT-003",
    brokerageName: "Atrium Realty Group",
    latitude: 30.3579,
    longitude: -97.9842,
    hoaFee: 175,
    taxAnnual: 15800,
    pricePerSqft: 213,
    openHouseDate: "2024-04-27",
  },
  {
    mlsId: "MLS-2024-008",
    address: "5501 Balcones Drive",
    city: "Austin",
    state: "TX",
    zip: "78731",
    listPrice: 699000,
    originalListPrice: 720000,
    sqft: 2400,
    bedrooms: 3,
    bathrooms: 2.5,
    garageSpaces: 2,
    yearBuilt: 2005,
    lotSize: 0.22,
    propertyType: "Single Family",
    status: "Pending",
    daysOnMarket: 11,
    listDate: "2024-04-11",
    closedDate: null,
    closedPrice: null,
    description: "Classic Northwest Austin home in Rosedale-adjacent neighborhood. Timeless design with hardwoods, updated kitchen, and large backyard. Minutes to Domain and 360.",
    features: ["Hardwood Floors", "Updated Kitchen", "Large Backyard", "Fireplace"],
    photos: ["https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Jordan Reeves",
    agentId: "AGT-001",
    brokerageName: "Atrium Realty Group",
    latitude: 30.3661,
    longitude: -97.7631,
    hoaFee: null,
    taxAnnual: 13200,
    pricePerSqft: 291,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-009",
    address: "211 West Lynn Street #203",
    city: "Austin",
    state: "TX",
    zip: "78703",
    listPrice: 565000,
    originalListPrice: 565000,
    sqft: 1450,
    bedrooms: 2,
    bathrooms: 2,
    garageSpaces: 1,
    yearBuilt: 2019,
    lotSize: 0,
    propertyType: "Condo",
    status: "Coming Soon",
    daysOnMarket: 0,
    listDate: "2024-04-25",
    closedDate: null,
    closedPrice: null,
    description: "Brand-new Clarksville condo with designer interiors. Rare opportunity in one of Austin's most walkable neighborhoods. Chef's kitchen, spa bath, and covered terrace.",
    features: ["Terrace", "Chef's Kitchen", "Clarksville Location", "Concierge", "Package Room"],
    photos: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&auto=format&fit=crop&q=80"],
    agentName: "James Okafor",
    agentId: "AGT-002",
    brokerageName: "Atrium Realty Group",
    latitude: 30.2823,
    longitude: -97.7633,
    hoaFee: 390,
    taxAnnual: 11000,
    pricePerSqft: 390,
    openHouseDate: null,
  },
  {
    mlsId: "MLS-2024-010",
    address: "8820 Brushy Creek Road",
    city: "Round Rock",
    state: "TX",
    zip: "78681",
    listPrice: 478000,
    originalListPrice: 499000,
    sqft: 2650,
    bedrooms: 4,
    bathrooms: 3,
    garageSpaces: 2,
    yearBuilt: 2011,
    lotSize: 0.16,
    propertyType: "Single Family",
    status: "Expired",
    daysOnMarket: 94,
    listDate: "2024-01-19",
    closedDate: null,
    closedPrice: null,
    description: "Spacious Round Rock home in great school district. Recent updates include new HVAC and interior paint. Large game room upstairs and covered patio.",
    features: ["Game Room", "Covered Patio", "New HVAC", "Cul-de-sac"],
    photos: ["https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&auto=format&fit=crop&q=80"],
    agentName: "Marcus Webb",
    agentId: "AGT-003",
    brokerageName: "Atrium Realty Group",
    latitude: 30.5311,
    longitude: -97.6789,
    hoaFee: 45,
    taxAnnual: 9100,
    pricePerSqft: 180,
    openHouseDate: null,
  },
];

export const clients: Client[] = [
  {
    id: "CLT-001",
    firstName: "Jennifer",
    lastName: "Walsh",
    email: "jennifer.walsh@gmail.com",
    phone: "(512) 555-0188",
    status: "Active Buyer",
    type: "Buyer",
    budget: 900000,
    preApproved: true,
    assignedListings: ["MLS-2024-001", "MLS-2024-007"],
    notes: "Relocating from Chicago for a tech role at Dell. Wants a family home in West Austin or Westlake. Must have a pool — two kids. Pre-approved at $900k through First Texas Bank.",
    lastContact: "2024-04-21",
    createdAt: "2024-03-20",
    source: "Referral",
    preferences: {
      maxBudget: 900000,
      minBedrooms: 4,
      minBathrooms: 3,
      preferredTypes: ["Single Family"],
      preferredCities: ["Austin"],
      preferredZips: ["78731", "78746"],
      mustHaveFeatures: ["Pool"],
      niceToHaveFeatures: ["Smart Home", "Outdoor Kitchen", "Solar Panels"],
    },
  },
  {
    id: "CLT-002",
    firstName: "Brian",
    lastName: "Nakamura",
    email: "b.nakamura@techco.com",
    phone: "(737) 555-0871",
    status: "Active Seller",
    type: "Seller",
    budget: null,
    preApproved: false,
    assignedListings: ["MLS-2024-006"],
    notes: "Selling Barton Hills estate. Very motivated — new job in Seattle starts May 15. Already closed.",
    lastContact: "2024-04-15",
    createdAt: "2024-02-20",
    source: "Past Client",
  },
  {
    id: "CLT-003",
    firstName: "Chloe",
    lastName: "Washington",
    email: "chloe.w@gmail.com",
    phone: "(512) 555-0319",
    status: "Active Buyer",
    type: "Buyer",
    budget: 500000,
    preApproved: true,
    assignedListings: ["MLS-2024-003", "MLS-2024-005"],
    notes: "First-time buyer. Wants condo in 78701 or 78704. Loves walkability. Pre-approved at $500k.",
    lastContact: "2024-04-20",
    createdAt: "2024-04-01",
    source: "Zillow Inquiry",
  },
  {
    id: "CLT-004",
    firstName: "David",
    lastName: "Osei",
    email: "dosei@corpventures.com",
    phone: "(512) 555-0588",
    status: "Closed",
    type: "Buyer",
    budget: 1300000,
    preApproved: true,
    assignedListings: ["MLS-2024-002"],
    notes: "Closed on Westlake home. Moving family from Houston. Very happy with process.",
    lastContact: "2024-04-17",
    createdAt: "2024-02-01",
    source: "Agent Referral",
  },
  {
    id: "CLT-005",
    firstName: "Elena",
    lastName: "Russo",
    email: "elena.russo@design.co",
    phone: "(737) 555-0234",
    status: "Lead",
    type: "Both",
    budget: 700000,
    preApproved: false,
    assignedListings: [],
    notes: "Interior designer interested in selling current home and buying up. Not pre-approved yet. Follow up re: lender referral.",
    lastContact: "2024-04-10",
    createdAt: "2024-04-10",
    source: "Open House",
  },
  {
    id: "CLT-006",
    firstName: "Frank",
    lastName: "Delgado",
    email: "frank.delgado@austinlaw.com",
    phone: "(512) 555-0967",
    status: "Active Seller",
    type: "Seller",
    budget: null,
    preApproved: false,
    assignedListings: ["MLS-2024-008"],
    notes: "Selling NW Austin home. Pending offer accepted at $699k. Expects smooth close by May 31.",
    lastContact: "2024-04-22",
    createdAt: "2024-03-28",
    source: "Sphere",
  },
  {
    id: "CLT-007",
    firstName: "Grace",
    lastName: "Kim",
    email: "gracekim.atx@gmail.com",
    phone: "(737) 555-0445",
    status: "Nurture",
    type: "Buyer",
    budget: 400000,
    preApproved: false,
    assignedListings: [],
    notes: "Interested in buying in 12-18 months. Student loan payoff in progress. Keep warm with monthly market updates.",
    lastContact: "2024-03-15",
    createdAt: "2024-01-22",
    source: "Social Media",
  },
  {
    id: "CLT-008",
    firstName: "Henry",
    lastName: "Blackwood",
    email: "hblackwood@investors.net",
    phone: "(512) 555-0732",
    status: "Active Buyer",
    type: "Buyer",
    budget: 2000000,
    preApproved: true,
    assignedListings: ["MLS-2024-009"],
    notes: "Investor looking for luxury condo or small multifamily. Cash buyer. Wants quick close.",
    lastContact: "2024-04-21",
    createdAt: "2024-04-05",
    source: "Referral",
  },
];

export const notes: Note[] = [
  {
    id: "NOTE-001",
    body: "Jennifer Walsh completed her second showing of 4821 Westbrook Lane. Strong interest — she loves the pool and outdoor kitchen. Wants to bring her husband this weekend before deciding.",
    authorName: "Jordan Reeves",
    createdAt: "2024-04-21T14:30:00Z",
    relatedClientId: "CLT-001",
    relatedMlsId: "MLS-2024-001",
    tag: "showing",
  },
  {
    id: "NOTE-002",
    body: "Pre-approval letter received for Jennifer Walsh. First Texas Bank approved up to $900,000 at 6.875% fixed. Valid through July 1, 2024.",
    authorName: "Jordan Reeves",
    createdAt: "2024-04-20T09:15:00Z",
    relatedClientId: "CLT-001",
    tag: "financing",
  },
  {
    id: "NOTE-003",
    body: "Frank Delgado accepted full-price offer on 5501 Balcones Drive — $699,000. Buyer financing contingency due May 3. Target close May 31.",
    authorName: "Jordan Reeves",
    createdAt: "2024-04-22T09:00:00Z",
    relatedClientId: "CLT-006",
    relatedMlsId: "MLS-2024-008",
    tag: "offer",
  },
  {
    id: "NOTE-004",
    body: "Open house at 3388 Lakeway Boulevard set for April 27, 1–4pm. Flyers printed, social posts scheduled. Expecting 10–15 groups based on online interest.",
    authorName: "Marcus Webb",
    createdAt: "2024-04-19T11:00:00Z",
    relatedMlsId: "MLS-2024-007",
    tag: "general",
  },
  {
    id: "NOTE-005",
    body: "910 Barton Hills Drive officially closed at $1,610,000. Brian Nakamura very pleased. Referred us to two colleagues relocating from Seattle.",
    authorName: "Jordan Reeves",
    createdAt: "2024-04-12T17:00:00Z",
    relatedClientId: "CLT-002",
    relatedMlsId: "MLS-2024-006",
    tag: "closing",
  },
  {
    id: "NOTE-006",
    body: "Price reduction on 8820 Brushy Creek Road from $499k to $478k after 94 days. Will notify relevant buyers in that price range today.",
    authorName: "Marcus Webb",
    createdAt: "2024-04-19T10:05:00Z",
    relatedMlsId: "MLS-2024-010",
    tag: "price",
  },
];

export const dashboardStats = {
  activeListings: mlsListings.filter((l) => l.status === "Active").length,
  pendingListings: mlsListings.filter((l) => l.status === "Pending").length,
  closedThisMonth: 2,
  totalVolumeThisMonth: 2309000,
  avgDaysOnMarket: 14,
  avgListPrice: 742125,
  newLeadsThisWeek: 3,
  activeClients: clients.filter((c) => c.status === "Active Buyer" || c.status === "Active Seller").length,
};
